package tests

var Port = 7540
var DBFile = "../scheduler.db"
var FullNextDate = true
var Search = true
var Token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFeHAiOjE1NTA5NDY2ODksInBhc3N3b3JkIjpbMjQxLDEyMiwyMDAsODksMTUzLDE0MiwxNCwyNDAsMTMyLDIxLDU0LDIzNCw5Niw4NywzMywxNTIsNyw1OCwxNDQsMTYzLDE1MSwxNywxMTcsODQsMTYxLDk3LDIzMSwyMzAsMjIzLDIwLDkwLDM1XX0.6EW5F3OniuixFbec9UF7Xu8HG5ryRHzP5MugWK6K8GY"
